const { fetch, fetchAll } = require('../../lib/postgres')

const new_rahbar = `
    INSERT INTO Rabaryat (
        rahbar_mode,
        rahbar_img,
        rahbar_name_uz,
        rahbar_name_ru,
        rahbar_name_krl,
        rahbar_name_en,
        rahbar_lavozim_uz,
        rahbar_lavozim_ru,
        rahbar_lavozim_krl,
        rahbar_lavozim_en,
        rahbar_telefon,
        rahbar_pochta,
        rahbar_qabul_kunlari,
        rahbar_vazifalari_uz,
        rahbar_vazifalari_ru,
        rahbar_vazifalari_krl,
        rahbar_vazifalari_en,
        rahbar_faolyati_uz,
        rahbar_faolyati_ru,
        rahbar_faolyati_krl,
        rahbar_faolyati_en,
        rahbar_link_telegram,
        rahbar_link_instagram,
        rahbar_link_facebook
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24)   RETURNING *
`
const rahbarlar = `
    SELECT * FROM Rabaryat
`
const one_rahbar = `
    SELECT * FROM Rabaryat WHERE rahbar_id = $1
`
const update_rahbar = `
    UPDATE Rabaryat SET 
    rahbar_mode = $1,
    rahbar_img = $2,
    rahbar_name_uz = $3,  
    rahbar_name_ru = $4,
    rahbar_name_krl = $5,
    rahbar_name_en = $6,
    rahbar_lavozim_uz = $7,
    rahbar_lavozim_ru = $8,
    rahbar_lavozim_krl = $9,
    rahbar_lavozim_en = $10,
    rahbar_telefon = $11,
    rahbar_pochta = $12,
    rahbar_qabul_kunlari = $13,
    rahbar_vazifalari_uz = $14,
    rahbar_vazifalari_ru = $15,
    rahbar_vazifalari_krl = $16,
    rahbar_vazifalari_en = $17,
    rahbar_faolyati_uz = $18,
    rahbar_faolyati_ru = $19,
    rahbar_faolyati_krl = $20,
    rahbar_faolyati_en = $21,
    rahbar_link_telegram = $22,
    rahbar_link_instagram = $23,
    rahbar_link_facebook = $24 WHERE rahbar_id = $25
`
const rahbarni_ishtan_boshatish = `
    DELETE FROM Rabaryat WHERE rahbar_id = $1
`
const new_Rahbar = (rahbar_mode,
    rahbar_img,
    rahbar_name_uz,
    rahbar_name_ru,
    rahbar_name_krl,
    rahbar_name_en,
    rahbar_lavozim_uz,
    rahbar_lavozim_ru,
    rahbar_lavozim_krl,
    rahbar_lavozim_en,
    rahbar_telefon,
    rahbar_pochta,
    rahbar_qabul_kunlari,
    rahbar_vazifalari_uz,
    rahbar_vazifalari_ru,
    rahbar_vazifalari_krl,
    rahbar_vazifalari_en,
    rahbar_faolyati_uz,
    rahbar_faolyati_ru,
    rahbar_faolyati_krl,
    rahbar_faolyati_en,
    rahbar_link_telegram,
    rahbar_link_instagram,
    rahbar_link_facebook) => fetch(new_rahbar, 
        rahbar_mode,
        rahbar_img,
        rahbar_name_uz,
        rahbar_name_ru,
        rahbar_name_krl,
        rahbar_name_en,
        rahbar_lavozim_uz,
        rahbar_lavozim_ru,
        rahbar_lavozim_krl,
        rahbar_lavozim_en,
        rahbar_telefon,
        rahbar_pochta,
        rahbar_qabul_kunlari,
        rahbar_vazifalari_uz,
        rahbar_vazifalari_ru,
        rahbar_vazifalari_krl,
        rahbar_vazifalari_en,
        rahbar_faolyati_uz,
        rahbar_faolyati_ru,
        rahbar_faolyati_krl,
        rahbar_faolyati_en,
        rahbar_link_telegram,
        rahbar_link_instagram,
        rahbar_link_facebook)
const Rahbaryat = () => fetchAll(rahbarlar)
const one_Rahbar = (rahbar_id) => fetch(one_rahbar, rahbar_id) 
const update_Rahbaryat = (
    rahbar_mode,
        rahbar_img,
        rahbar_name_uz,
        rahbar_name_ru,
        rahbar_name_krl,
        rahbar_name_en,
        rahbar_lavozim_uz,
        rahbar_lavozim_ru,
        rahbar_lavozim_krl,
        rahbar_lavozim_en,
        rahbar_telefon,
        rahbar_pochta,
        rahbar_qabul_kunlari,
        rahbar_vazifalari_uz,
        rahbar_vazifalari_ru,
        rahbar_vazifalari_krl,
        rahbar_vazifalari_en,
        rahbar_faolyati_uz,
        rahbar_faolyati_ru,
        rahbar_faolyati_krl,
        rahbar_faolyati_en,
        rahbar_link_telegram,
        rahbar_link_instagram,
        rahbar_link_facebook,
         rahbar_id
)=> fetch(update_rahbar,
    rahbar_mode,
        rahbar_img,
        rahbar_name_uz,
        rahbar_name_ru,
        rahbar_name_krl,
        rahbar_name_en,
        rahbar_lavozim_uz,
        rahbar_lavozim_ru,
        rahbar_lavozim_krl,
        rahbar_lavozim_en,
        rahbar_telefon,
        rahbar_pochta,
        rahbar_qabul_kunlari,
        rahbar_vazifalari_uz,
        rahbar_vazifalari_ru,
        rahbar_vazifalari_krl,
        rahbar_vazifalari_en,
        rahbar_faolyati_uz,
        rahbar_faolyati_ru,
        rahbar_faolyati_krl,
        rahbar_faolyati_en,
        rahbar_link_telegram,
        rahbar_link_instagram,
        rahbar_link_facebook,
         rahbar_id    
)
const delete_Rahbar = (rahbar_id) => fetch(rahbarni_ishtan_boshatish, rahbar_id) 

module.exports = {
    new_Rahbar,
    Rahbaryat,
    one_Rahbar,
    update_Rahbaryat,
    delete_Rahbar
}